# Generated by Django 3.2.3 on 2021-05-26 03:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_auto_20210525_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productapp.categories'),
            preserve_default=False,
        ),
    ]
