# Generated by Django 3.2.3 on 2021-05-28 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0007_alter_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productapp.categories'),
        ),
    ]
